### ISSUE TITLE
Should there be a zsh config?

### ISSUE THREAD

**Issue by pbizimis** [TheAvidDev/dotfiles#2]
Hey,
first of all, very awesome theme.

I am currently trying to understand how you configured everything and was wondering why there is no zsh config since the README mentions `.zsrc --> ~/.zshrc`.

Thank you and have a good day!

**Comment by fluix-dev** [comment]
Hey, thanks!

It was removed in f41781e3451f07d77b0faf4021cb80e773027547 and I haven't actually updated these in a *long* time. https://git.sr.ht/~fluix/dotfiles is a bit newer, but still not current, and is missing many files.

I don't think I'll be updating this repository, but I may do so with the sr.ht one, at which point I'll add a message redirecting users there.

**Comment by pbizimis** [comment]
Thanks for the info :+1:
